handlers/protectedAreas/GET/index.js
handlers/protectedAreas/_orcs/GET/index.js
layers/dataUtils/protectedAreas.js
template.yaml

Adding GET `/protected-areas` and GET `/protected-areas/{orcs}`

Adding protected area GETs (single & collection)

---

lib/handlers/geozones/resources.js

BRS-56
#56 
- fix misnamed file after `geozoneId` update

BRS-56-1: Add CRUD for Geozones (fix)

---

docs/postman/BCParks PRDT Reservation System.postman_collection.json
lib/layers/dataUtils/facilities/methods.js

BRS-57
#57 
- Fix an issue with type mismatch between `facilityType`/`facilityId` and the `sk`
- Update Postman and add some scripts to make testing easier

BRS-57-1: Add CRUD for Facilities (fix)

---

lib/layers/dataUtils/facilities/configs.js

PRDT-70-4 minor changes to facility config

---

lib/layers/dataUtils/facilities/configs.js

relates to #69, #70. Should have been included in earlier commit.

PRDT-70-6 Changes to facilities config

---

docs/postman/BCParks PRDT Reservation System.postman_collection.json
lib/handlers/activities/_acCollectionId/POST/index.js
lib/handlers/activities/_acCollectionId/PUT/index.js
lib/handlers/facilities/_fcCollectionId/DELETE/index.js
lib/handlers/facilities/_fcCollectionId/POST/index.js
lib/handlers/facilities/_fcCollectionId/PUT/index.js
lib/handlers/geozones/_gzCollectionId/DELETE/index.js
lib/handlers/geozones/_gzCollectionId/GET/index.js
lib/handlers/geozones/_gzCollectionId/POST/index.js
lib/handlers/geozones/_gzCollectionId/PUT/index.js
lib/handlers/geozones/resources.js
lib/layers/awsUtils/dynamodb.js
lib/layers/dataUtils/activities/configs.js
lib/layers/dataUtils/activities/methods.js
lib/layers/dataUtils/facilities/configs.js
lib/layers/dataUtils/facilities/methods.js
lib/layers/dataUtils/geozones/configs.js
lib/layers/dataUtils/geozones/methods.js

Revert as per this request: https://github.com/bcgov/reserve-rec-api/issues/89#issuecomment-2837132009
Will revisit this feature change in the future after #69  and #70 are merged in and apply updates accordingly to better fit the data model.

Revert "PRDT-89: Auto Increment on Post Requests"

---

lib/handlers/bookings/resources.js

PRDT-98-3 updating bookingsPolicy references

---

lib/handlers/facilities/resources.js

found the real culprit finally

giving facilities BatchGetItem permissions

---

lib/handlers/tooling/protectedAreas/syncFromDataRegister/index.js
lib/handlers/tooling/resources.js

Accidental committal of API key and the `syncFromTantalisFunction`. API Key cycled.

removing api key

---

docs/postman/BCParks PRDT Reservation System.postman_collection.json

Adding Postman endpoints for bookings so they can be tested.

PRDT-98 adding Postman for QA testing

---

lib/handlers/bcsc/GET/index.js
lib/handlers/bcsc/POST/index.js
lib/handlers/bcsc/resources.js
lib/reserve-rec-cdk-stack.js

Ticket: [43](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=113164891&issue=bcgov%7Creserve-rec-admin%7C43)
Notes: We need to make a proxy request to BCSC in order to decrypt userInfo, this request will be coming from Cognito but needs to be routed through our api to include the additional logic. Currently This logic is left out but will still give us an opportunity to reformat the BCSC response into a format readable for Cognito. BCSC has offered to send unencrypted through DEV instance for time being so we can slowly work through the additional steps required with this work flow.

PRDT-43: Admin Login

---

lib/handlers/bcsc/resources.js

Fixing the resource file broken from last PR

PRDT-43: Fix the Resource file

---

lib/handlers/bcsc/GET/index.js
lib/handlers/bcsc/POST/index.js

Removing debug statements previously required for live development.

PRDT: 43: Admin Login

---

lib/cdk/lambda.js
lib/handlers/bcsc/GET/index.js
lib/handlers/bcsc/resources.js
lib/layers/jwt/jwt.js
lib/layers/jwt/nodejs/package.json
lib/reserve-rec-cdk-stack.js
package.json

First steps in setting up for BCSC encryption/decryption. 
jwks GET endpoint JWT layer implementation.

BRS 71: Prep for token encryption

---

lib/handlers/bcsc/GET/index.js
lib/handlers/bcsc/resources.js

Notes: Was getting a timeout increasing to debug. 
Adjust whitespace in lambda to force rebuild.

Increase Timeout, Rebuild lambda

---

lib/handlers/bcsc/GET/index.js
lib/handlers/bcsc/resources.js
lib/layers/jwt/jwt.js

notes: Use valid RSA encryption, increase memory, force rebuild of lambda.

Change encryption to acceptable format

---

lib/layers/jwt/jwt.js

Hardcode the keys to see if the workflow can function properly.

Hardcode Keys for testing

---

.github/workflows/deploy-api-dev.yaml
bin/reserve-rec-cdk.js
lib/handlers/bcsc/GET/index.js
lib/handlers/bcsc/resources.js
lib/layers/jwt/jwt.js
lib/layers/jwt/nodejs/package.json

Notes: 
* Build with KMS
* Use keys from kms
* Removed hard coded keys

Use kms instead of hardcoded keys

---

lib/handlers/bcsc/GET/index.js

Await the decryption function
Removed unnecessary console log that cause error

Await the decryption, Remove substring log

---

lib/cdk/cognito-admin.js
lib/cdk/cognito-public.js

Using ESP to predict that generating a CfnOutput for userpoolArns was the problem all along

PRDT-171-7 Removing CFN exports to userpool ARNS

---

lib/cdk/cognito-admin.js
lib/cdk/cognito-public.js
lib/handlers/users/resources.js
lib/reserve-rec-cdk-stack.js

Backing out everything to do with non-existent userpool
