bcgov/reserve-rec-api

docs/postman/BCParks PRDT Reservation System.postman_collection.json, lib/handlers/protectedAreas/DELETE/index.js, lib/handlers/protectedAreas/POST/index.js, lib/handlers/protectedAreas/_orcs/DELETE/index.js, lib/handlers/protectedAreas/_orcs/GET/index.js, lib/handlers/protectedAreas/_orcs/POST/index.js, lib/handlers/protectedAreas/resources.js, lib/layers/dataUtils/data-utils.js, lib/layers/dataUtils/protectedAreas/configs.js, lib/layers/dataUtils/validation-rules.js
BRS-55
#55
- First-pass at adding endpoints for Protected Areas
- Add new `POST` endpoint for creating `protectedArea`s
- Add new `POST` endpoint for creating single `protectedArea` by `orcs`
- Update validation rules to support creation operations
- Add new configuration for `protectedArea` creation
- Update Postman collection with new endpoints
- `GET` to `/protection-areas/` retrieves all `protectedArea`s
- `POST` to `/protection-areas/` with an array of `protectedArea`-acceptable data attributes in the `body` of the request will create multiple `protectedArea`s.
- Can't create a `PUT` without  `orcs` in the body, but `orcs` is also the sk and therefore would indicate this is a new item. `POST` allows overwrite (for now)
- `DELETE` to `/protection-areas/` with an array of `sk`s in the …
=> BRS-55: Add CRUD for Protected Areas

docs/postman/BCParks PRDT Reservation System.postman_collection.json, lib/handlers/activities/_orcs/DELETE/index.js, lib/handlers/activities/_orcs/GET/index.js, lib/handlers/activities/_orcs/POST/index.js, lib/handlers/activities/_orcs/PUT/index.js, lib/handlers/activities/resources.js, lib/layers/dataUtils/activities/configs.js, lib/layers/dataUtils/activities/constants.js, lib/layers/dataUtils/activities/methods.js, lib/reserve-rec-cdk-stack.js
BRS-58
#58 
- First-pass at adding endpoints for Activities
- Add new `GET`, `POST`, `PUT`, and `DELETE` endpoints for `activities` by orcs
- allow batch requests or single requests
- use `queryParams` like `activityType=dayuse` or `activityId=1` to specify specific items in the partition
- allow further filtering on `GET` requests using `ALLOWED_FILTERS`, such as by `facilities`, `subActivityType`, or `isVisible`
- Add new configuration for `activities` creation
- Add constants folder for `ALLOWED_FILTERS`
- Update Postman collection with new endpoints
=> BRS-58: Add CRUD for Activities

lib/layers/dataUtils/data-utils.js, lib/layers/dataUtils/geozones/configs.js, lib/layers/dataUtils/validation-rules.js
Relates to #70, #69 
Minor updates to the Geozone CRUD ops to support minor changes to the data model that have been made recently.
Listing the minor changes below:
- Changing the default `quickApiPutHandler` dynamodb operation to 'set' (was 'add). Both functions are fundamentally equivalent except 'add' is typically used when an existing value must be considered, which will never be the case for this function (use `quickApiUpdateHandler` in that situation).
- Adding a `expectPrimaryKey` config function for checking whether or not a property is structured as a dynamodb primary key. Due to the desire to move away from ORCS as the backbone for the data model, we must now list the whole primary key (pk + sk) when cross linking datapoints. We can no longer infer the primary key from other …
=> PRDT-70-1 CRUD updates for geozones

lib/handlers/dynamoStream/index.js, lib/handlers/geozones/resources.js
Relates to #69, #70
The `dynamodb:Update*` policy action is necessary to perform DynamoDB's UpdateItem command (used in all PUTs). Note: We will have to update the permissions of the other put functions at a later time. 
Also included in this PR: restricting the datatypes that are forwarded to OpenSearch. If an incoming image has a schema that is not included in the `schemasTransferrable` list, it will not be forwarded to OpenSearch (or the audit log, or websockets, for now. This will have to be modified later).
=> PRDT-70-2: Adding `dynamodb:Update*` role to geozone PUT

lib/handlers/facilities/resources.js
Facilities resources missing the `dynamodb:Update*` permissions.
=> PRDT-70-5 Adding  permissions to facilities

docs/postman/BCParks PRDT Reservation System.postman_collection.json, lib/handlers/activities/_acCollectionId/POST/index.js, lib/handlers/activities/_acCollectionId/PUT/index.js, lib/handlers/facilities/_fcCollectionId/DELETE/index.js, lib/handlers/facilities/_fcCollectionId/POST/index.js, lib/handlers/facilities/_fcCollectionId/PUT/index.js, lib/handlers/geozones/_gzCollectionId/DELETE/index.js, lib/handlers/geozones/_gzCollectionId/GET/index.js, lib/handlers/geozones/_gzCollectionId/POST/index.js, lib/handlers/geozones/_gzCollectionId/PUT/index.js, lib/handlers/geozones/resources.js, lib/layers/awsUtils/dynamodb.js, lib/layers/dataUtils/activities/configs.js, lib/layers/dataUtils/activities/methods.js, lib/layers/dataUtils/facilities/configs.js, lib/layers/dataUtils/facilities/methods.js, lib/layers/dataUtils/geozones/configs.js, lib/layers/dataUtils/geozones/methods.js
BRS-89
#89 
Refactor activity request handling, update validation logic, and add counter support
- Update to Geozone
- `resource.js`
- update `pathParameters` to be camelCase (applies to GET, POST, PUT, and DELETE)
- POST
- requests are now `async` to allow increment transaction with Dynamo
- remove `geozoneId` as this now auto increments and the user cannot specify in POST request
- PUT
- requests are now `async` as increment transactions are within same method
- DELETE
- Remove unused `validateSortKey` import.
- `method.js`
- Rework functions to allow for `null` IDs (for auto increment)
- Remove `validateSortKey` function. Make it more strict to build sk, and do not allow `sk` to be passed in as an item (must be created from `geozoneId`).
- ActivityID is optional, as it might only be …
=> PRDT-89: Auto Increment on Post Requests

lib/handlers/products/_byPartition/GET/index.js, lib/handlers/products/resources.js, lib/layers/awsUtils/dynamodb.js, lib/layers/dataUtils/activities/configs.js, lib/layers/dataUtils/products/methods.js, lib/reserve-rec-cdk-stack.js
Relates to #69 and #70.
Adding `GET Products` endpoint. Subject to change based on the outcome of the scheduling data model changes.
```
GET products/acCollectionId/activityType/activityId/seasonId/productId
```
If queryParams `getPolicies=true` is passed in, the internal policies within the product are queried and populated by Dynamodb `BatchGET`.
=> adding Products GET and minor changes to facilitate data insertion

lib/handlers/tooling/opensearch/createMainIndex/index.js
Adding geozone, facilities, activities, and policies as `object` field mapping types by default in opensearch
=> changing default mainIndex mappings

lib/cdk/dynamodb.js, lib/handlers/dynamoStream/resources.js
Relates to #106.
The DEV main table was orphaned and recreated from a PITR backup. The CDK stack is unable to accept any newly created DynamoDB resources unless they are imported and attached back to the AWS stack.
There are methods to achieve this import properly: https://aws.amazon.com/blogs/database/use-point-in-time-recovery-to-restore-an-amazon-dynamodb-table-managed-by-aws-cdk/, but in an effort to unblock developers while this method is fleshed out, I have implemented a temporary fix.
The main table reference is now generated from the PITR table's ARN, so the references should be correct. The drawback is that the table and its settings can no longer be managed by CDK.
This change only comments out the existing Table constructs, so they can be reintroduced later.
=> PRDT-106-1: Temporary fix to try and unblock devops by creating main table by TableARN

lib/cdk/dynamodb.js, lib/handlers/activities/resources.js, lib/handlers/bookings/GET/index.js, lib/handlers/bookings/POST/index.js, lib/handlers/bookings/resources.js, lib/layers/awsUtils/dynamodb.js, lib/layers/dataUtils/activities/configs.js, lib/layers/dataUtils/bookings/configs.js, lib/layers/dataUtils/bookings/methods.js, lib/layers/dataUtils/data-constants.js, lib/layers/dataUtils/data-utils.js, lib/layers/dataUtils/facilities/configs.js, lib/layers/dataUtils/geozones/configs.js, lib/layers/dataUtils/policies/configs.js, lib/layers/dataUtils/protectedAreas/configs.js, lib/layers/dataUtils/validation-rules.js, lib/reserve-rec-cdk-stack.js
Relates to #98 .
Adding Bookings GET and POST endpoints to contribute to the E2E. Note that the data structure for bookings used in this change is not finalized but rather a temporary datatype that should support the E2E without any of the verification processes.
Waiting on previous changes to the AWS remote instance to be fixed before merging, but this code is finished for now. 
Currently, database items are uniquely identified distinctly from their sibling items using a logically incremented `identifier`: 1, 2, 3 etc. This method is great when the data items are relatively static and dont change often, and we want the primary keys of the items to be somewhat logically enumerated and guessable by humans for ease of access.
Bookings are the first datatype we have encountered in this …
=> PRDT-98 Adding Bookings POST/GET

lib/cdk/dynamodb.js
Relates to #106 and #98
UUID GSI must be manually created in the web console since we are temporarily constructing the main table by ARN reference instead of via CDK.
=> PRDT-98-2 Removing UUID GSI CDK construct

lib/layers/dataUtils/validation-rules.js
Relates to #98 
Fix to `expectPrimaryKey` validation function. The function was missing the `expectObjectToOnlyHaveProperties` method, which checks if the object _only_ contains `pk` and `sk` in the object. No longer insta-fails on check.
=> PRDT-98-5: Fix to expectPrimaryKey Validation

lib/handlers/activities/resources.js, lib/handlers/facilities/resources.js, lib/handlers/geozones/resources.js, lib/reserve-rec-cdk-stack.js
Relates to #97 
Add permissions to `geozones`, `facilities`, and `activities` so the resources can interact with `reserve-rec-counter` table.
=> BRS-97: Fix to Permissions for Counter Table

lib/layers/awsUtils/dynamodb.js
Relates to #97 
Fix to `resetCounter` as `:initialValue` is expecting a value to be a string.
=> BRS-97-5: Fix to resetCounter Function

lib/layers/awsUtils/dynamodb.js
Relates to #97.
Fix a similar issue where `:counterValue` expects a string, and properly throw the error if it occurs.
=> BRS-97: Fix to incrementCounter and Error Throws

lib/layers/awsUtils/dynamodb.js
Relates to #97.
Fix to an infinite loop when counter is not existent and there are no existing items in the main table.
=> BRS-97-6: Fix when Counter Needs a Reset vs Initialization

lib/layers/dataUtils/geozones/configs.js
Relates to #97. Fix to geozone config following changes to data model and how `activities` and `facilities` are saved.
=> BRS-97-7: Fix geozone config

lib/handlers/bookings/resources.js
relates to #98 
apparently indexes aren't automagically included when blessing functions with table access policies
=> PRDT-98: adding permissions to new GSI

lib/layers/dataUtils/bookings/configs.js, lib/layers/dataUtils/data-utils.js, lib/layers/dataUtils/validation-rules.js
Relates to [983644](https://github.com/bcgov/reserve-rec-public/issues/65)
Some minor changes to the bookings API configuration such that the API can receive forms values straight from the front end. 
Namely a major update to the `data-utils.js` Data Layer code such that the validation step of `quickAPIPutHandler` can handle arrays of complex objects being passed in as a field. The vehicle field can receive more than one of the same type of object: 
```
[
{
"licensePlate": "ABC 123",
"licensePlateRegistrationRegion": "British Columbia"
},
{
"licensePlate": "XYZ 789",
"licensePlateRegistrationRegion": "Alberta"
}
]
```
^ Is now permissible and verifiable in the POST body.
=> PRDT-65 updating bookings api to match FE designs

lib/handlers/bookings/GET/index.js, lib/handlers/tooling/protectedAreas/syncFromDataRegister/index.js, lib/handlers/tooling/resources.js, lib/layers/dataUtils/bookings/configs.js, lib/layers/dataUtils/bookings/methods.js, lib/layers/dataUtils/data-utils.js, lib/layers/dataUtils/geozones/methods.js, lib/layers/dataUtils/validation-rules.js, lib/reserve-rec-cdk-stack.js, package.json
Relates to #65 
Added the ability to pull nested information by their pk/sk with the use of a new function in `data-utils`, `getAndAttachNestedProperties`. This is used elsewhere but since the use case crops up often a reusable function was written for the case of bookings and their entry/exit points.
Also bookings was missing 'displayName' as a mandatory field.
=> PRDT-65-2 fetch nested entry/exit facilities on bookings GET

lib/layers/dataUtils/bookings/configs.js, lib/layers/dataUtils/data-utils.js, lib/layers/dataUtils/validation-rules.js
Originally had planned for the 'user' field to be empty if a booking was made with a guest account, so this code was added to allow a field to be submitted to the quickAPIHandlers as blank (all the validation rules would be ignored). 
Turns out 'user' is a field used in a GSI so it cannot be blank, but this code still holds for other fields.
Guest accounts will now have no user field.
=> PRDT-65 updating quickAPIHandlers to allow empty fields

lib/layers/dataUtils/data-utils.js
Relates to #98. In `/layers/dataUtils/data-utils/getAndAttachNestedProperties`, an error is thrown if the item's property  doesn't exist or is an empty array. Instead, the code should provide a warning and continue.
=> Don't attempt to call nested properties if there are none

lib/handlers/activities/_acCollectionId/DELETE/index.js, lib/handlers/activities/_acCollectionId/PUT/index.js, lib/handlers/activities/resources.js, lib/handlers/bookings/resources.js, lib/handlers/facilities/_fcCollectionId/DELETE/index.js, lib/handlers/facilities/_fcCollectionId/POST/index.js, lib/handlers/geozones/_gzCollectionId/DELETE/index.js, lib/handlers/geozones/resources.js, lib/layers/awsUtils/dynamodb.js, lib/layers/dataUtils/activities/configs.js, lib/layers/dataUtils/facilities/configs.js, lib/layers/dataUtils/geozones/methods.js
PRDT-59, PRDT-58
[#59](https://github.com/bcgov/reserve-rec-admin/issues/59), [#58](https://github.com/bcgov/reserve-rec-admin/issues/58)
- Activities endpoints
- Modified DELETE and PUT endpoints for activities from `/activities/{acCollectionId}` to `/activities/{acCollectionId}/{activityType}/{activityId}`
- Updated DELETE endpoint for geozones from `/geozones/{gzCollectionId}` to `/geozones/{gzCollectionId}/{geozoneId}`
- Refactored parameter extraction to use path parameters instead of query string parameters
- Activities handler updates
- DELETE handler now extracts `activityType` and `activityId` from path parameters instead of query parameters
- PUT handler parameter logic with fallback to query parameters for backwards compatibility
- Added nested resource structure …
=> PRDT-59 and 58: facilities, geozones, and activities fixes for CRUD
